In [1]:
import numpy as np
a1=np.array([1,2,3,4])      #1D array
print(a1)
a2=np.array([[1,2,3,4], [5,6,7,8]])        #2D array
print(a2)
a3=np.array([1,2,3,4,5,6,7,8,9,10,11,12], ndmin=3) #3D array
print(a3)
a3.ndim

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[[[ 1  2  3  4  5  6  7  8  9 10 11 12]]]


3

In [1]:
# why use array instead of list
import sys
import numpy as np
l = range(1000)
print(sys.getsizeof(5) * len(l))      #prints size of the list

arr = np.arange(1000)
print(arr.size * arr.itemsize)         #prints size of the array

28000
8000


In [12]:
import time                          # speed of numpy array is much faster than list
import numpy as np
size = 1000000

#list
l1 = range(size)
l2 = range(size)
start = time.time()
result = [(x + y) for x,y in zip(l1,l2)]
print("speed of list : ",(time.time() - start) * 1000)

#numpy array
start = time.time()
arr1 = np.arange(size)
arr2 = np.arange(size)
result = arr1 + arr2
print("speed of numpy array : ",(time.time() - start) * 1000)

speed of list :  114.10212516784668
speed of numpy array :  15.388727188110352


In [46]:
a = np.array([1,2,3,4,5], dtype = np.int8)
print(a)
a.itemsize

[1 2 3 4 5]


1

In [14]:
a = np.zeros((3,4), dtype = int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [16]:
a = np.arange(1, 5, 2)
print(a)

[1 3]


In [40]:
a3 = np.array([[[1,2], [4, 5], [7, 8]]])
a3.reshape(6,1)

array([[1],
       [2],
       [4],
       [5],
       [7],
       [8]])

In [39]:
a3.ravel()    #make the array linear   

array([1, 2, 4, 5, 7, 8])

In [26]:
a3.min()

1

In [27]:
a3.max()

8

In [28]:
a3.sum()   #sums up all the elements

27

In [29]:
a3.sum(axis = 0)      # axis 0 is along the column

array([12, 15])

In [30]:
a3.sum(axis = 1)         #axis 1 is along the row

array([ 3,  9, 15])

In [33]:
np.sqrt(a3)        # square root

array([[1.        , 1.41421356],
       [2.        , 2.23606798],
       [2.64575131, 2.82842712]])

In [41]:
np.std(a)     #standard eviation

1.0